[tool.poetry]
name = "fluwid_agent"
version = "0.1.0"
description = "Custom implementation of LiveKit's Voice Pipeline Agent"
authors = ["Teodor Georgiev <teodor.georgiev@fluwid.ai>"]
readme = "README.md"
package-mode = true
packages = [{include = "fluwid_agent"}]

[tool.poetry.dependencies]
python = "^3.12.1"
python-dotenv = "^1.0.1"
pymongo = "4.10.1"
livekit-agents = "^0.12.13"
livekit-plugins-anthropic = "^0.2.10"
livekit-plugins-deepgram = "^0.6.19"
livekit-plugins-elevenlabs = "^0.7.13"
livekit-plugins-silero = "^0.7.4"
pytest = "^8.3.5"

[tool.poetry.group.dev.dependencies]
black = "^24.2.0"
isort = "^5.13.2"
flake8 = "^7.0.0"

[tool.poetry.scripts]
fluwid = "fluwid_agent.main:main"

[tool.pytest.ini_options]
testpaths = ["tests"]
addopts = "-v -ra -q"
python_files = "test_*.py"
python_functions = "test_*"
markers = [
    "slow: marks tests as slow (deselect with '-m \"not slow\"')",
]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api" 